openapi: '3.0.3'
info:
  version: 1.0.0
  title: TODO API
  description: TODO
paths:
  /env:
    summary: Gets the public API environment data
    get:
      operationId: getEnvironmentInfo
      summary: Gets the public API environment data
      responses:
        200:
          description:
            Contains public environment info that is still useful for developers
            when debugging issues
          content:
            application/json:
              schema:
                type: object
                required:
                  - gitHash
                  - tag
                properties:
                  gitHash:
                    description: Git commit hash
                    type: string
                  tag:
                    description: Build tag id
                    type: string
